name: Supabase DB Backup

on:
  schedule:
    - cron: '0 3 * * *'  # Todos los días a las 3:00 AM UTC
  workflow_dispatch:     # También puedes ejecutarlo manualmente

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Set current timestamp
        id: timestamp
        run: echo "NOW=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV

      - name: Install Supabase CLI
        run: |
          curl -L -o supabase.tar.gz https://github.com/supabase/cli/releases/download/v1.156.3/supabase-cli-linux-amd64.tar.gz
          tar -xzf supabase.tar.gz
          sudo mv supabase /usr/local/bin

      - name: Login to Supabase CLI
        run: supabase login --access-token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Dump Supabase database
        run: |
          mkdir -p backups
          supabase db dump --project-ref tmxhsqexsxnizmsffzad --db-url "postgres://postgres:${{ secrets.DB_PASSWORD }}@tmxhsqexsxnizmsffzad.supabase.co:6543/postgres" > backups/db_backup_${{ env.NOW }}.sql

      - name: Upload backup
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup-${{ env.NOW }}
          path: backups/db_backup_${{ env.NOW }}.sql
