name: Supabase DB Backup

on:
  schedule:
    - cron: '0 3 * * *'  # Diario a las 3am UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Set current timestamp
        run: echo "NOW=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV

      - name: Install Supabase CLI
        run: |
          curl -L -o supabase.tar.gz https://github.com/supabase/cli/releases/download/v2.26.9/supabase_linux_amd64.tar.gz
          tar -xzf supabase.tar.gz
          sudo mv supabase /usr/local/bin

      - name: Set Supabase access token
        run: echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Dump Supabase database using local config
        run: |
          mkdir -p backups
          supabase db dump \
            --file backups/db_backup_${{ env.NOW }}.sql \
            --workdir .supabase

      - name: Upload backup to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup-${{ env.NOW }}
          path: backups/db_backup_${{ env.NOW }}.sql
